---
- name: Create temporary file
  tempfile:
  register: tempfile

- name: Download install script
  get_url: 
    url: https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh
    dest: "{{ tempfile.path }}"
    force: yes
    mode: 0700

- name: Chek if snoopy is already installed
  stat:
    path: /usr/local/sbin/snoopy-enable
  register: snoopyfiles

- name: Run install script
  shell:
    cmd: '"{{ tempfile.path }}" stable'
  when: 
    - snoopyfiles.stat.exists == false

- name: Remove temporary file
  file:
    path: "{{ tempfile.path }}"
    state: absent
  when: tempfile.path is defined

- name: Attempting to overlay snoopy configurations
  tags: snoopy
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: snoopy.ini.j2, dst: /etc/snoopy.ini }
    - { src: ld.so.preload.j2, dst: /etc/ld.so.preload }
  loop_control:
    label: "{{ item.dst.split('/')[2] }}"
...
