---
- name: Check if snoopy is already installed
  tags: snoopy
  become: true
  stat:
    path: /usr/local/sbin/snoopy-enable
  register: snoopyfiles

- block:
    - name: Create temporary file
      tags: snoopy
      become: true
      tempfile:
      register: tempfile

    - name: Download install script
      tags: snoopy
      become: true
      get_url: 
        url: https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh
        dest: "{{ tempfile.path }}"
        force: yes
        mode: 0700

    - name: Run install script
      tags: snoopy
      become: true
      shell:
        cmd: '"{{ tempfile.path }}" stable'
    
    - name: Remove temporary file
      tags: snoopy
      become: true
      file:
        path: "{{ tempfile.path }}"
        state: absent
  when: 
    - snoopyfiles.stat.exists == false


- name: Attempting to overlay snoopy configurations
  tags: snoopy
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: snoopy.ini.j2, dst: /etc/snoopy.ini }
    - { src: ld.so.preload.j2, dst: /etc/ld.so.preload }
  loop_control:
    label: "{{ item.dst.split('/')[2] }}"
...
