---
- name: Ensure that the snoopy package is installed
  tags: snoopy
  become: true
  yum:
    enablerepo: "linuxhq-{{ linuxhq_pkg }}"
    name: snoopy
    state: present

- name: Attempting to overlay snoopy configurations
  tags: snoopy
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: snoopy.ini.j2, dst: /etc/snoopy.ini }
    - { src: ld.so.preload.j2, dst: /etc/ld.so.preload }
  loop_control:
    label: "{{ item.dst.split('/')[2] }}"
...
