---
- name: Download install script
  ansible.builtin.get_url: 
    url: https://github.com/a2o/snoopy/raw/install/install/install-snoopy.sh
    dest: /tmp/install-snoopy.sh
    force: yes
  delegate_to: localhost
  run_once: true

- name: Chek if snoopy is already installed
  ansible.builtin.stat:
    path: /usr/local/sbin/snoopy-enable
  register: snoopyfiles

- name: Run install script
  ansible.builtin.script:
    cmd: /tmp/install-snoopy.sh stable
  when: 
    - snoopyfiles.stat.exists == false

- name: Attempting to overlay snoopy configurations
  tags: snoopy
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - { src: snoopy.ini.j2, dst: /etc/snoopy.ini }
    - { src: ld.so.preload.j2, dst: /etc/ld.so.preload }
  loop_control:
    label: "{{ item.dst.split('/')[2] }}"
...
